name: Add label on merge conflict
on:
  pull_request_target:
    branches: [ main ]
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label Conflicting Pull Requests
        uses: eps1lon/actions-label-merge-conflict@v2.0.0
        with: 
          dirtyLabel: "TEST: merge-conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, so we need to resolve that! 
          don't worry at all let me help with you with that.
          please visit this link ---> https://github.com/twindle-co/twindle/issues/41."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
